name: Compendium
main: net.avicus.compendium.plugin.CompendiumPlugin
version: ${project.version}-${git.commit.id.abbrev}
authors:
- Avicus Network
depend:
#- ProtocolLib
softdepend:
- ProtocolSupport
- or
- ViaVersion
commands:
  set:
  setting:
  settings:
  toggle:
