name: Compendium
main: net.avicus.compendium.plugin.CompendiumPlugin
version: ${project.version}-${git.commit.id.abbrev}
authors:
- Avicus Network
depend:
- ProtocolLib
- ProtocolSupport
- BossBarAPI
commands:
  set:
  setting:
  settings:
  toggle:
